public class BasicCalculator {
    public integer firstnumber{get;set;}
    public integer secondnumber{get;set;}
    public integer Result{get;set;}
    public void Addition()
    {
        Result=firstnumber+secondnumber;
    }
     public void Subtraction()
    {
        Result=firstnumber-secondnumber;
    }
     public void Multiplication()
    {
        Result=firstnumber*secondnumber;
    }
     public void Division()
    {
        Result=firstnumber/secondnumber;
    }
    
    
}